game/urls.py
"""CMS urls."""
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [

    path(
        '',
        views.start_game,
        name='start-game'
    ),
    path(
        'juego/<int:game_id>/',
        views.GameDetailView.as_view(),
        name='game_detail'
    ),
    path(
        'juego/<int:game_id>/nueva_carta',
        views.new_card,
        name='new_card',
    ),

]

loteria/urls.py
"""Loteria URL Configuration."""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deck/models.py
"""Deck's Models."""
from django.db import models


class Card(models.Model):

    image = models.ImageField(
        'imagen',
        upload_to='images',
    )
    number = models.IntegerField(
        'numero',
    )
    name = models.CharField(
        'nombre',
        max_length=50,
    )
    cross_image = models.ImageField(
        'imagen',
        upload_to='cross_images',
        null=True,
    )

    class Meta:
        verbose_name = "Carta"
        verbose_name_plural = "Cartas"

    def __str__(self):
        return self.name

game/models.py
"""Game's Models."""
from django.db import models
from django.urls import reverse


class Game(models.Model):

    class Meta:
        verbose_name = "Juego"
        verbose_name_plural = "Juegos"

    def get_absolute_url(self):
        return reverse('game:game_detail', kwargs={'game_id': self.pk})


class Board(models.Model):

    game = models.ForeignKey(
        'Game',
        related_name='boards',
        on_delete=models.CASCADE,
    )
    player = models.CharField(
        'jugador',
        max_length=50,
    )

    class Meta:
        verbose_name = "Tablero"
        verbose_name_plural = "Tableros"

    def __str__(self):
        return self.player

    @property
    def not_checked_cards(self):
        list_cards = []
        for card in self.cards.all():
            if not (card.checked):
                list_cards.append(card.card.name)
        return list_cards

    def winner(self):
        cards = {}
        for card in self.cards.order_by('position'):
            cards[card.position] = card
        # Vertical Wins
        if cards[1].checked and cards[5].checked and cards[9].checked and cards[13].checked:
            return True
        elif cards[2].checked and cards[6].checked and cards[10].checked and cards[14].checked:
            return True
        elif cards[3].checked and cards[7].checked and cards[11].checked and cards[15].checked:
            return True
        elif cards[4].checked and cards[8].checked and cards[12].checked and cards[16].checked:
            return True
        # Horizontal Wins
        elif cards[1].checked and cards[2].checked and cards[3].checked and cards[4].checked:
            return True
        elif cards[5].checked and cards[6].checked and cards[7].checked and cards[8].checked:
            return True
        elif cards[9].checked and cards[10].checked and cards[11].checked and cards[12].checked:
            return True
        elif cards[13].checked and cards[14].checked and cards[15].checked and cards[16].checked:
            return True
        # Diagonal Wins
        elif cards[1].checked and cards[6].checked and cards[11].checked and cards[16].checked:
            return True
        elif cards[4].checked and cards[7].checked and cards[10].checked and cards[13].checked:
            return True
        else:
            return False


class GameCard(models.Model):

    board = models.ForeignKey(
        'Board',
        related_name='cards',
        on_delete=models.CASCADE,
    )
    position = models.IntegerField(
        'posicion',
    )
    card = models.ForeignKey(
        'deck.Card',
        on_delete=models.CASCADE,
    )
    checked = models.BooleanField(
        default=False,
    )

    class Meta:
        verbose_name = "Carta de Juego"
        verbose_name_plural = "Carta de Juegos"

    def __str__(self):
        return str(self.position)

deck/views.py
from django.shortcuts import render

# Create your views here.

game/views.py
"""Game's Views."""
import cv2
import numpy as np
from .models import (
    Game,
    Board,
    GameCard,
)
from deck.models import Card
from django.views.generic import (
    DetailView,
)
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from sklearn.tree import DecisionTreeClassifier
from skimage import io
from skimage.color import rgb2gray


def start_game(request):
    """Create a new game."""
    game = Game.objects.create()
    user_board = Board.objects.create(
        game=game,
        player='jugador',
    )
    computer_board = Board.objects.create(
        game=game,
        player='computadora',
    )
    count = 1
    for user_card in Card.objects.order_by('?')[:16]:
        user_game_card = GameCard(
            board=user_board,
            position=count,
            card=user_card,
        )
        user_game_card.save()
        count += 1
    count = 1
    for computer_card in Card.objects.order_by('?')[:16]:
        computer_game_card = GameCard(
            board=computer_board,
            position=count,
            card=computer_card,
        )
        computer_game_card.save()
        count += 1
    return HttpResponseRedirect(game.get_absolute_url())


class GameDetailView(DetailView):
    """Show the boards of two players."""

    model = Game
    pk_url_kwarg = "game_id"
    template_name = "game.html"
    context_object_game = "game"

    def get_context_data(self, **kwargs):
        """Get the context for the view."""
        context = super(GameDetailView, self).get_context_data(**kwargs)
        for board in self.object.boards.all():
            if board.player == 'jugador':
                context['player_board'] = board
            else:
                context['computer_board'] = board
        return context


def new_card(request, game_id):
    """Take a photo of a new card and detect if is in a board."""
    game = get_object_or_404(Game, pk=game_id)
    webcam = cv2.VideoCapture(0)
    check, frame = webcam.read()
    cv2.imwrite(filename='saved_img.jpg', img=frame)
    webcam.release()
    cv2.destroyAllWindows()

    image_saved = io.imread('saved_img.jpg')
    gray_saved = rgb2gray(image_saved)
    gray_saved = (gray_saved * 255) // 1
    [rows_saved, columns_saved] = gray_saved.shape
    for row in range(rows_saved):
        for column in range(columns_saved):
            if gray_saved[row, column] > 100:
                gray_saved[row, column] = 0
            else:
                gray_saved[row, column] = 255

    number1 = gray_saved[20:65, 200:240]
    number2 = gray_saved[20:65, 245:285]

    data = []
    labels = []

    for i in range(12):
        for j in '0123456789':
            image_name = 'data/{}-{}.jpg'.format(i, j)
            image = io.imread(image_name)
            gray = rgb2gray(image)
            gray = (gray * 255) // 1
            [rows, columns] = gray.shape

            for row in range(rows):
                for column in range(columns):
                    if gray[row, column] > 100:
                        gray[row, column] = 0
                    else:
                        gray[row, column] = 255

            for k in range(100):
                data.append(gray.reshape(1800))
                labels.append(j)

    data = np.array(data)
    labels = np.array(labels)

    clf = DecisionTreeClassifier()
    clf.fit(data, labels)

    test = np.array([number1.reshape(1800), number2.reshape(1800)])
    predictions = clf.predict(test)

    number = int(str(predictions[0]) + str(predictions[1]))
    try:
        card = Card.objects.get(name=number)
        text = card.name
        print(card.number)
    except:
        print('No card')

    for board in game.boards.all():
        if text in board.not_checked_cards:
            game_card = GameCard.objects.get(board=board, card__name=text)
            game_card.checked = True
            game_card.save()

    return HttpResponseRedirect(game.get_absolute_url())

templates/game.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>Game</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style type="text/css">
    body {
      background-image: url("{% static "img/fondo.jpg" %}");
      background-repeat: repeat;
    }
  </style>
</head>
<body>

  <div class="container">

    <div class="row">
      <!-- User Board -->
      <div class="col-6">
        <br>
        
        <div class="card">

          <div class="card-title">
            <h2>User Board</h2>
            <hr>
          </div>

          <div class="card-title">
            <div class="row">

              {% for user_card in player_board.cards.all %}
                <div class="col-3">
                  {% if user_card.checked %}
                    <div class="card" style="width: 60%;">
                      <img src="{{ user_card.card.cross_image.url }}" class="card-img-top" alt="...">
                    </div>
                  {% else %}
                    <div class="card" style="width: 60%;">
                      <img src="{{ user_card.card.image.url }}" class="card-img-top" alt="...">
                    </div>
                  {% endif %}
                </div>
              {% endfor %}

            </div>
          </div>

        </div>

      </div>

      <!-- Computer Board -->
      <div class="col-6">
        <br>
        
        <div class="card">

          <div class="card-title">
            <h2>Computer Board</h2>
            <hr>
          </div>

          <div class="card-title">
            <div class="row">

              {% for computer_card in computer_board.cards.all %}
                <div class="col-3">
                  {% if computer_card.checked %}
                    <div class="card" style="width: 60%;">
                      <img src="{{ computer_card.card.cross_image.url }}" class="card-img-top" alt="...">
                    </div>
                  {% else %}
                    <div class="card" style="width: 60%;">
                      <img src="{{ computer_card.card.image.url }}" class="card-img-top" alt="...">
                    </div>
                  {% endif %}
                </div>
              {% endfor %}

            </div>
          </div>

        </div>

      </div>
      <div class="row">
        {% if not player_board.winner and not computer_board.winner %}
          <a href="{% url 'game:new_card' game.id %}" class="btn btn-success">Nueva carta</a>
        {% elif not player_board.winner and computer_board.winner %}
          <div class="text-center">
            <h1>La Computadora gana</h1>
          </div>
        {% elif player_board.winner and not computer_board.winner %}
          <div class="text-center">
            <h1>Has ganado</h1>
          </div>
        {% elif player_board.winner and computer_board.winner %}
          <div class="text-center">
            <h1>Empate</h1>
          </div>
        {% endif %}
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>